name: media_flow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Fixed SDK constraint syntax

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5       # Added version constraint
  flutter_bloc: ^8.1.1
  bloc: ^8.1.3           # Added version constraint
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  go_router: ^14.4.1
  just_audio: ^0.9.42
  file_picker: ^5.2.3
  permission_handler: ^10.2.0
  marquee: ^2.2.3
  device_info_plus: ^11.1.1
  external_path: ^2.0.1
  flutter_pdfview: ^1.3.4
  video_player: ^2.9.2
  video_thumbnail_imageview: ^0.0.6
  on_audio_query_forked: ^2.9.1
  scrollable_positioned_list: ^0.3.8
  flutter_screenutil: ^5.9.3
  just_audio_background: ^0.0.1-beta.13
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13    # Moved to dev_dependencies
  hive_generator: ^2.0.1   # Moved to dev_dependencies

flutter:
  uses-material-design: true

  assets:
    - assets/images/